# Quality Gate Workflow
# Issue #36 - TOOL-CICD-001
# Runs tests, coverage, security scanning, and code quality checks

name: Quality Gate

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  quality-gate:
    name: Quality Gate Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better analysis

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r issue_36_requirements.txt

      - name: Run tests with coverage
        run: |
          pytest \
            --cov=. \
            --cov-report=xml:coverage.xml \
            --cov-report=json:coverage.json \
            --cov-report=html:htmlcov \
            --cov-report=term \
            --junitxml=test-results.xml \
            -v

      - name: Check coverage threshold
        run: |
          python -c "
          import json
          with open('coverage.json') as f:
              data = json.load(f)
              coverage = data['totals']['percent_covered']
              threshold = 80.0
              print(f'Coverage: {coverage:.2f}%')
              if coverage < threshold:
                  print(f'ERROR: Coverage {coverage:.2f}% below threshold {threshold}%')
                  exit(1)
              print(f'SUCCESS: Coverage {coverage:.2f}% meets threshold {threshold}%')
          "

      - name: Run Bandit security scan
        run: |
          bandit -r . \
            -f json \
            -o security-report.json \
            --exclude ./tests,./htmlcov,./.venv \
            --skip B101 \
            || true  # Don't fail, just report

      - name: Check security issues
        run: |
          python -c "
          import json
          with open('security-report.json') as f:
              data = json.load(f)
              results = data.get('results', [])
              high = sum(1 for r in results if r.get('issue_severity') == 'HIGH')
              medium = sum(1 for r in results if r.get('issue_severity') == 'MEDIUM')
              low = sum(1 for r in results if r.get('issue_severity') == 'LOW')
              print(f'Security issues: HIGH={high}, MEDIUM={medium}, LOW={low}')
              if high > 0:
                  print(f'ERROR: {high} high-severity security issues found')
                  exit(1)
              print('SUCCESS: No high-severity security issues')
          "

      - name: Run Flake8
        run: |
          flake8 . \
            --exclude=.venv,htmlcov,tests \
            --max-line-length=88 \
            --extend-ignore=E203,W503 \
            --format=json \
            --output-file=flake8-report.json \
            || true

      - name: Run Pylint
        run: |
          pylint issue_36_*.py \
            --output-format=json \
            --reports=y \
            > pylint-report.json \
            || true

      - name: Run MyPy type checking
        run: |
          mypy issue_36_*.py \
            --ignore-missing-imports \
            --no-strict-optional \
            --json-report mypy-report \
            || true

      - name: Calculate code complexity
        run: |
          radon cc . -a -s -j > complexity-report.json || true
          radon mi . -s -j > maintainability-report.json || true

      - name: Generate quality report
        run: |
          python -c "
          import json
          from datetime import datetime

          # Aggregate all reports
          report = {
              'timestamp': datetime.now().isoformat(),
              'workflow': 'quality_gate',
              'branch': '${{ github.ref_name }}',
              'commit': '${{ github.sha }}',
              'reports': {}
          }

          # Coverage
          try:
              with open('coverage.json') as f:
                  report['reports']['coverage'] = json.load(f)
          except: pass

          # Security
          try:
              with open('security-report.json') as f:
                  report['reports']['security'] = json.load(f)
          except: pass

          # Code quality
          try:
              with open('complexity-report.json') as f:
                  report['reports']['complexity'] = json.load(f)
          except: pass

          with open('quality-gate-report.json', 'w') as f:
              json.dump(report, f, indent=2)

          print('Quality gate report generated')
          "

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.xml
            coverage.json
            htmlcov/
          retention-days: 90

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: security-report.json
          retention-days: 90

      - name: Upload quality reports
        uses: actions/upload-artifact@v4
        with:
          name: quality-reports
          path: |
            flake8-report.json
            pylint-report.json
            complexity-report.json
            maintainability-report.json
            quality-gate-report.json
          retention-days: 90

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results.xml
          retention-days: 30

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const coverage = JSON.parse(fs.readFileSync('coverage.json', 'utf8'));
            const coveragePct = coverage.totals.percent_covered.toFixed(2);

            const security = JSON.parse(fs.readFileSync('security-report.json', 'utf8'));
            const securityIssues = security.results.length;

            const comment = `## Quality Gate Report

            **Coverage:** ${coveragePct}% (threshold: 80%)
            **Security Issues:** ${securityIssues}

            ${coveragePct >= 80 ? '✅' : '❌'} Coverage check
            ${securityIssues === 0 ? '✅' : '⚠️'} Security scan

            [View detailed reports](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
